version: "3"

services:
  api:
    build: ./api
    volumes:
      - ./api:/go/src/github.com/coacer/go-web-sample/api
      - api-lib:/go/src/github.com
    ports:
      - 8080:8080
    depends_on:
      - db
    tty: true
    command: go run main.go

  client:
    build: ./client
    volumes:
      - ./client:/app
      - client-lib:/app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    tty: true
    command: npm run dev

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go-web-sample
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  api-lib:
  client-lib:
  db-data:
